cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
auth:
  base-url: ${AUTH_BASE_URL:http://auth-service:8080}
spring:
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  r2dbc:
    properties:
      sslMode: REQUIRE

security:
  jwt:
    secret: ${SPRING_JWT_SECRET:23A522D4A614E645267556B58703273357638792F423F4528482B4D6251655468}

adapters:
  r2dbc:
    host: ${SPRING_R2DBC_HOST:localhost}
    port: ${SPRING_R2DBC_PORT:5432}
    database: ${SPRING_R2DBC_DATABASE:ms-auth-crediya}
    schema: "public"
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:mysecretpassword}